# Generated by Django 4.2 on 2024-06-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lliga', '0002_partit_detalls_partit_inici_partit_local_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugador',
            old_name='numero',
            new_name='edat',
        ),
        migrations.AddField(
            model_name='equip',
            name='ciutat',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lliga',
            name='temporada',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
